#!/bin/bash
# The Edge Detector Node (EDN) script. Starts EDN.
echo "Script Edge Detector Node"


# Select launch file
echo "Select launch file: "
select filename in "video" "image" "gstreamer-lab-summer" "gstreamer-lab-roof" "gstreamer-udp-camera-front" "lab"; do
	case $filename in
		video ) roslaunch edge_detector_node video.launch; break;;
		image ) roslaunch edge_detector_node image-sim-r2.launch; break;;
		gstreamer-lab-summer ) roslaunch edge_detector_node gstreamer-lab-summer.launch; break;;
		gstreamer-lab-roof ) roslaunch edge_detector_node gstreamer-lab-roof.launch; break;;
		gstreamer-udp-camera-front ) roslaunch edge_detector_node gstreamer-udp-camera-front.launch; break;;
		lab ) roslaunch edge_detector_node lab.launch; break;;
	esac
done


$SHELL
sleep 5
