#!/bin/bash
#The Drone Master script
echo "Drone Master"

echo "Do you want to start resource monitoring (GPU)?"
select yn in "Yes" "No"; do
	case $yn in
		Yes ) x-terminal-emulator -e '/bin/bash -c "watch nvidia-smi"'; break;;
		No ) break;;
	esac
done

#Start ROS Core
echo "Start ROS Core"
x-terminal-emulator -e '/bin/bash -c "roscore"'
sleep 2

#ROS Pre Rviz
echo "Start MAP (Pre Rviz)"
rosrun tf static_transform_publisher 0.0 0.0 0.0 0.0 0.0 0.0 map my_frame 100 &
sleep 1

#ROS Rviz
echo "Start Rviz"
rosrun rviz rviz &

#Show ps to indicate system status
ps &
sleep 3

# Start the edge detector?
echo "Do you want to start the edge detector node?"
select answer in "yes" "no" "single"; do
	case $answer in
		yes ) x-terminal-emulator -e '/bin/bash /home/ascend/scripts/dronemaster/start_edge_detector'; break;;
		no ) break;;
		single ) x-terminal-emulator -e '/bin/bash /home/ascend/scripts/dronemaster/edge_detector'; break;;
	esac
done


# Start the gstreamer-reciver?
echo "Do you want to start the gstreamer-reciver node?"
select answer in "yes" "no"; do
	case $answer in
		yes ) x-terminal-emulator -e '/bin/bash /home/ascend/scripts/dronemaster/gstreamer_reciver'; break;;
		no ) break;;
	esac
done



